desisu/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('food/', include('food.urls', namespace='food'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('rice', views.rice, name = 'rice'),
    path('chicken', views.chicken, name = 'chicken'),
    path('mutton_beef', views.mutton_beef, name='mutton_beef'),
    path('bbq', views.bbq, name='bbq'),
    path('roti', views.roti, name='roti'),
    path('starters', views.starters, name='starters'),
    path('pasta', views.pasta, name='pasta'),
    path('durum', views.durum, name='durum'),
    path('chinese', views.chinese, name='chinese'),
    path('veg', views.veg, name='veg'),
    path('sweet', views.sweet, name='sweet'),
    path('addons', views.addons, name='addons'),
    path('drinks', views.drinks, name='drinks'),
    path('burger', views.burger, name='burger'),
    path('rolls', views.rolls, name='rolls'),
    path('salads', views.salads, name='salads'),
    path('soup', views.soup, name='soup'),
    path('saute', views.saute, name='saute'),
    path('order', views.order, name = 'order'),
    path('success', views.success, name = 'success'),
    path('signup', views.signup, name = 'signup'),
    path('employee', views.employee, name = 'employee'),
    path('dispatchRider', views.dispatchRider, name = 'dispatchRider'),
    path('arrived', views.arrived, name = 'arrived'),
    path('verify_otp', views.verify_otp, name = 'verify_otp'),
    path('login', views.logIn, name = 'login'),
    path('logout', views.logOut, name = 'logout'),
    path('reset_password', views.reset_password, name = 'reset_password'),
    path('verify_reset_otp', views.verify_reset_otp, name = 'verify_reset_otp'),
    path('profile', views.profile, name = 'profile'),
    path('topup', views.topup, name = 'topup'),
    path('about_us', views.about_us, name = 'about_us'),
    path('addToWallet', views.addToWallet, name = 'addToWallet'),
    path('all_orders', views.same_date_orders, name = 'all_orders'),
    path('summary', views.summary, name = 'summary'),
    path('food/cancel_order/<str:number>/', views.cancel_order, name='cancel_order'),
    path('food/prepare/<str:number>/', views.prepare, name="prepare"),
    path('api/get_orders_received_today/', views.get_orders_received_today, name='get_orders_received_today'),
    path('check_wallet_balance/', views.check_wallet_balance, name='check_wallet_balance'),
    path('submit_payment/', views.payment_submission, name='payment_submission'),    
    path('reply/<int:feedback_id>', views.reply, name='reply'),  
    path('unsub/<str:username>/', views.unsub, name="unsub"),
    path('download_excel', views.download_excel, name="download_excel"),
    path('api/confirm_orders/' , views.confirm_orders, name='confirm_orders'),
    path('feedback', views.feedback, name='feedback'),
    path('allMessages', views.allMessages, name='allMessages'),
    path('support', views.support, name='support')
]

food/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser, BaseUserManager
from datetime import date
import random
import string

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)  # Use EmailField for authentication
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    university = models.CharField(max_length=20, blank=True, null=True) 
    wallet_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    otp = models.CharField(max_length=6, blank=True, null=True)  # Add this field for OTP

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'  # Set the email field as the username field
    REQUIRED_FIELDS = []  # Specify any additional required fields for user creation

    def __str__(self):
        return self.email
    


class NotificationStatus(models.Model):
    mailing_list_sent = models.BooleanField(default=False)
    last_updated = models.DateField(default='2000-01-01')

class MailingList(models.Model):
    email = models.EmailField(unique=True)

class TopUp(models.Model):
    customer = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    topUpAmount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=10)
    receipt = models.ImageField(upload_to='payments/')    

class UserProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    orders = models.ManyToManyField('Order')

    def __str__(self):
        return self.user.username
    
class WhatsappNums(models.Model):
    number = models.CharField(max_length=20)
    date = models.DateField(auto_now_add=True, blank=True)

class Rice(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Rimage = models.ImageField(upload_to='rice_images/')

class ChickenMain(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    CMimage = models.ImageField(upload_to='chickenMain_images/')

class MuttonBeef(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    MBimage = models.ImageField(upload_to='muttonBeef_images/')

class Roti(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Rimage = models.ImageField(upload_to='roti_images/')

class BBQ(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    BBQimage = models.ImageField(upload_to='bbq_images/')

class Burger(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Bimage = models.ImageField(upload_to='burger_images/')

class Rolls(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Rimage = models.ImageField(upload_to='roll_images/')

class Salads(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Simage = models.ImageField(upload_to='salad_images/') 

class Starter(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Simage = models.ImageField(upload_to='starter_images/')

class Veg(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Vimage = models.ImageField(upload_to='veg_images/')

class Soup(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Simage = models.ImageField(upload_to='soup_images/')

class Chinese(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Cimage = models.ImageField(upload_to='chinese_images/')

class Sweet(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Simage = models.ImageField(upload_to='sweet_images/')

class Drinks(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Dimage = models.ImageField(upload_to='drink_images/')

class Durum(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Simage = models.ImageField(upload_to='durum_images/')

class Addons(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    Simage = models.ImageField(upload_to='addon_images/')    

class ChickenSaute(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    CSimage = models.ImageField(upload_to='saute_images/')

class RamadanSpecial(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    CSimage = models.ImageField(upload_to='ramadan_images/')    

class Pasta(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    CSimage = models.ImageField(upload_to='pasta_images/')        

class Order(models.Model):
    customer = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    number = models.CharField(max_length=60)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(auto_now_add=True, blank=True)
    time = models.TimeField(auto_now=True, blank=True)
    address = models.CharField(max_length=60)
    note = models.TextField(blank=True, null=True)
    confirmed = models.BooleanField(default=False)
    prepared = models.BooleanField(default=False)

    def __str__(self):
        return f"Order {self.number}"

class Item(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

class Payments(models.Model):
    receipt = models.ImageField(upload_to='payments/')
    date = models.DateField(auto_now_add=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, default="Pending")

class FAQs(models.Model):
    question = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)

class Feedback(models.Model):
    email = models.CharField(max_length = 80)
    name = models.CharField(max_length = 150)
    feedback = models.CharField(max_length = 300)

food/forms.py
from food.models import CustomUser, Feedback
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
import re

class NewUserForm(UserCreationForm):
    email = forms.EmailField(max_length=100, required=True, help_text='Enter your Sabanci email address')
    phone_number = forms.CharField(max_length=15, required=True, help_text='Phone number must have the format 05xxx')

    class Meta:
        model = CustomUser
        fields = ['email', 'first_name', 'last_name', 'phone_number', 'password1', 'password2']
        help_texts = {
            'password1': None,
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')

        # Check if the email matches the "username@sabanciuniv.edu" format
        if not re.match(r'^[a-zA-Z0-9._%+-]+@sabanciuniv\.edu$', email):
            raise forms.ValidationError("Email must be in the format 'username@sabanciuniv.edu'.")

        return email

class OTPForm(forms.Form):
    otp = forms.CharField(max_length=6, required=True, help_text='Enter the OTP sent to your email')

    def clean_otp(self):
        otp = self.cleaned_data.get('otp')

        # Get the user from the request
        user = self.request.user

        # Check if the user's profile has an OTP set
        if not user.profile.otp:
            raise forms.ValidationError("No OTP has been generated for this user. Please register or request a new OTP.")

        # Check if the entered OTP matches the one in the user's profile
        if otp != user.profile.otp:
            raise forms.ValidationError("Invalid OTP. Please check your email for the correct OTP.")

        return otp
    

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'email', 'feedback']

food/templates/food/about_us.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} About Us {% endblock %}

{% block content %}
<style>
    .rounded-container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f8f8f8;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 20px;
    }

    h2, h3 {
        color: #333;
    }

    p {
        color: #666;
        line-height: 1.6;
    }

    h3 {
        margin-top: 20px;
    }

    /* Add any additional styles based on your design preferences */
</style>

<div class="rounded-container">
    <h2 class="text-center">About Us</h2>
    <p>Welcome to Royal Taj, your home for authentic Indian and Pakistani cuisine in Pendik and Kurtkoy! With a legacy spanning four years, we take pride in bringing the true essence of Indian and Pakistani dishes to your plate.</p>
 <!-- Add the image here -->
    <img src="/media/RoyalTaj.jpg" alt="Royal Taj Restaurant" style="max-width: 100%; border-radius: 10px; margin-top: 20px; margin-bottom: 20px">
    <h3>🌟 Our Mission:</h3>
    <p>At Royal Taj, we strive for excellence and aim to deliver a taste experience that goes beyond the ordinary. Our commitment to quality ingredients and traditional recipes ensures each dish is a celebration of flavor.</p>

    <h3>👩‍🍳 Chef's Specials:</h3>
    <p>Explore a diverse menu curated by our skilled chefs who infuse passion into every creation. From classic favorites to innovative delights, there's something to satisfy every palate.</p>

    <h3>🎓 Student Subsidies:</h3>
    <p>We understand the importance of good food on a student's journey. That's why we've introduced subsidized rates exclusively for Sabanci students. Quality meals at affordable prices - because great taste should be accessible to everyone.</p>

    <h3>📍 Our Locations:</h3>
    <p>Visit us in Pendik and Kurtkoy to experience a culinary journey that transports you to the heart of India and Pakistan. Our warm and inviting ambiance complements the richness of our dishes.</p>

    <h3>🤝 Thank You for Four Wonderful Years:</h3>
    <p>As we celebrate four years of serving you, we express our gratitude for your continued support. Join us at Royal Taj, where every meal is a celebration of tradition, taste, and togetherness.</p>
</div>
{% endblock %}

food/templates/food/allMessages.html
<!-- food/allMessages.html -->

{% extends 'food/base.html' %}
{% load static %}
{% block title %} Employee Menu {% endblock %}

{% block content %}
<div class="rounded-container" style="text-align: center; padding-bottom: 80px; margin-top: 20px;">
    <style>
        table {
            border-collapse: collapse;
            text-align: center;
            width: 90%;
            margin: 0 auto;  /* Center the table */
            border-radius: 10px;  /* Add rounded border */
            overflow: hidden;  /* Ensure the border radius is applied */
            margin-top: 20px; /* Add space between the table and the container */
        }

        th, td {
            border: 1px solid #dddddd;
            padding: 12px;
        }

        th {
            background-color: #381f1f;
            text-align: center;
            font-size: 20px;
            color: white;
        }

        td {
            padding-left: 20px;  /* Adjust the value to your preference */
            font-size: 20px;
        }
    </style>
    <h2 class="p-3">All messages</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Message</th>
                <th>Reply</th>
            </tr>
        </thead>
        <tbody>
            {% for feedback_item in feedback_items %}
            <tr>
                <td>{{ feedback_item.name }}</td>
                <td>{{ feedback_item.email }}</td>
                <td>{{ feedback_item.feedback }}</td>
                <td><a href="{% url 'food:reply' feedback_item.id %}" class="btn btn-success">Reply</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<style>
@media (max-width: 768px) {
    table {
        width: 100% !important;
    }
}
</style>
{% endblock %}

food/templates/food/employee.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} Employee Menu {% endblock %}

{% block content %}
    <style>
        .commands-container {
            text-align: center;
        }

        .small-text {
            display: block;
            margin-top: -15px; /* Adjust the margin to align it properly */
        }
    </style>
<div class="rounded-container" style="text-align: center; padding-bottom: 80px;">
<div class="commands-container">
        <h1 style="padding-bottom: 40px; padding-top: 40px;">Commands</h1>
        <small class="small-text">Do not use the download button before 5 pm</small>
        <a class="btn btn-success mr-4" href="{% url 'food:dispatchRider' %}">Dispatch Rider</a>
        <a class="btn btn-success mr-4" href="{% url 'food:download_excel' %}">Download Excel file</a>
        <a class="btn btn-success mr-4" href="{% url 'food:summary' %}">View Summary</a>
    </div>

    <h1 style="text-align: center; padding-bottom: 40px; padding-top: 40px;">Orders placed today</h1>

    <style>
        table {
            border-collapse: collapse;
            text-align: center;
            width: 90%;
            margin: 0 auto;  /* Center the table */
            border-radius: 10px;  /* Add rounded border */
            overflow: hidden;  /* Ensure the border radius is applied */
        }

        th, td {
            border: 1px solid #dddddd;
            padding: 12px;
        }

        th {
            background-color: #381f1f;
            text-align: center;
            font-size: 20px;
            color: white;
        }

        td {
            padding-left: 20px;  /* Adjust the value to your preference */
            font-size: 20px;

        }
    </style>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Items</th>
                <th>Phone number</th>
                <th>Address</th>
                <th>Total (Inlcuding delivery)</th>
                <th>Note / Special request</th>
                <th>Preparation status</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.customer.first_name }} {{ order.customer.last_name }}</td>
                <td>
                    <ul>
                        {% for item in order.item_set.all %}
                            <li>{{ item.name }}, Price: {{ item.price }} TL</li>
                        {% endfor %}
                        <li>Delivery charges: 10 TL </li>
                    </ul>
                </td>
                <td>{{ order.customer.phone_number }}</td>
                <td>{{ order.address }}</td>
                <td>{{ order.total|add:10 }} TL</td>
                <td>{{ order.note }}</td>
                {% if order.prepared == False %}
                <td><a href="{% url 'food:prepare' order.number %}" class="btn btn-danger">Prepare</a></td>
                {% else %}
                <td>Already prepared</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<style>
@media (max-width: 768px) {
    table {
        width: 100% !important;
    }
}
</style>
{% endblock %}

food/templates/food/login.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} Login {% endblock %}

{% block content %}
    <div class="container-fluid p-5 d-flex justify-content-center align-items-center" style="background-color: #ffffff; height: 70vh;">
        <div class="rounded-container p-5 text-dark rounded" style="width: 400px; background-color: #ffffff; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
            <h3 class="text-center mb-4">Login</h3>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="email" class="form-control" placeholder="Email">
                </div>  
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary btn-block mt-3">Login</button>
            </form>
            <div class="mt-3">
                <p class="text-center">Not registered? <a href="{% url 'food:signup' %}">Sign up now</a></p>
                <p class="text-center"><a href="{% url 'food:reset_password' %}">Forgot your password?</a></p>
            </div>
            {% if messages %}
                <ul class="pt-2 text-center">
                    {% for msg in messages %}
                    <li style="color: red;">{{ msg }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

food/templates/food/profile.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} Profile {% endblock %}

{% block content %}
<h1 class="pt-3 text-center" style="padding: 20px;">Welcome {{ user.first_name }}</h1>
<div class="rounded-container" style="text-align: center; width: 50%; margin: 0 auto;">
    {% if messages %}
        {% for message in messages %}
            <h5{% if message.tags %} class="{{ message.tags }} pt-2"{% endif %}>{{ message }}</h5>
        {% endfor %}
    {% endif %}

    <h3 class="pt-4">Your details are as follows:</h3>
    <div class="d-flex justify-content-between p-5">
        <div class="rounded-container-inner" style="text-align: center; margin: 0 auto;">
            <h5 class="pt-3">First Name: {{ user.first_name }}</h5>
            <h5 class="pt-3">Last Name: {{ user.last_name }}</h5>
            <h5 class="pt-3">Phone Number: {{ user.phone_number }}</h5>
        </div>
    </div>
    <h3 class="pt-4">Orders:</h3>
    <button id="toggleTodayOrders" class="btn btn-success mb-3">Show Today's Orders</button>
    <div id="todayOrdersContainer" class="table pt-3" style="display: none;">
        <h4>Today's Orders</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>Order Number</th>
                    <th>Total</th>
                    <th>Date</th>
                    <th>Confirmed</th>
                    <th>Cancel</th>
                </tr>
            </thead>
            <tbody>
                {% for order in today_orders %}
                <tr>
                    <td>{{ order.number }}</td>
                    <td>{{ order.total }}</td>
                    <td>{{ order.date }}</td>
                    <td>{{ order.confirmed }}</td>
                    {% if order.date == today_date %}
                        <td><a href="{% url 'food:cancel_order' order.number %}" class="btn btn-danger">Cancel</a></td>
                    {% endif %}
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No orders today.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <button id="togglePastOrders" class="btn btn-success mb-3">Show Past Orders</button>
    <div id="pastOrdersContainer" class="table pt-3" style="display: none;">
        <h4>Past Orders</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>Order Number</th>
                    <th>Total</th>
                    <th>Date</th>
                    <th>Confirmed</th>
                </tr>
            </thead>
            <tbody>
                {% for order in past_orders %}
                <tr>
                    <td>{{ order.number }}</td>
                    <td>{{ order.total }}</td>
                    <td>{{ order.date }}</td>
                    <td>{{ order.confirmed }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No past orders.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<style>
    .rounded-container-inner {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 15px;
        border-radius: 10px;
        background-color: white;
    }

    /* Media Query for smaller screens */
    @media (max-width: 768px) {
        .rounded-container {
            width: 100% !important;
        }
    }
</style>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var todayOrdersContainer = document.getElementById('todayOrdersContainer');
        var toggleTodayOrdersButton = document.getElementById('toggleTodayOrders');
        
        var pastOrdersContainer = document.getElementById('pastOrdersContainer');
        var togglePastOrdersButton = document.getElementById('togglePastOrders');

        toggleTodayOrdersButton.addEventListener('click', function () {
            if (todayOrdersContainer.style.display === 'none') {
                todayOrdersContainer.style.display = 'block';
            } else {
                todayOrdersContainer.style.display = 'none';
            }
        });

        togglePastOrdersButton.addEventListener('click', function () {
            if (pastOrdersContainer.style.display === 'none') {
                pastOrdersContainer.style.display = 'block';
            } else {
                pastOrdersContainer.style.display = 'none';
            }
        });
    });
</script>
{% endblock %}

food/templates/food/reset_password.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} Reset Password {% endblock %}

{% block content %}

    <div class="container-fluid p-5 d-flex justify-content-center align-items-center" style="background-color: #ffffff; margin-top: 10px;">
        <div class="rounded-container p-5 text-dark rounded" style="width: 400px; background-color: #ffffff; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
            <h3 class="text-center mb-4">Reset Password</h3>
            <form method="POST">
                {% csrf_token %}

                <!-- Display error message if any -->
                {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endif %}

                <div class="form-group">
                    <input type="email" name="email" id="id_email" class="form-control" placeholder="Email" required>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-3">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}